# Generated by Django 6.0.3 on 2026-05-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
